spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native

  application:
    name: note-config-center

server:
  port: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka/
